package zte.net.ecsord.common;

/**
 * 接口静态常量定义
 * @author Administrator
 *
 */
public class StypeConsts {

	//字典编码常量定义【es_dc_public_dict_relation】
	public static final String PRODUCT_TYPE = "product_type";//商品系统与总部货品类型映射
	public static final String DIC_PACKAGE_TYPE = "DIC_PACKAGE_TYPE";//合约计划映射
	public static final String CARD_TIME = "CARD_TIME";//卡时长映射
	public static final String SIM_TYPE = "SIM_TYPE";//卡种类映射
	
	
	//常用静态数据字典编码stype【es_dc_public_dict_relation】
	public static final String WMS_GOODS_TYPE = "wms_goods_type";//wms商品类型映射
	public static final String WMS_CARD_TYPE = "wms_card_type";
	 public static final String BAI_CARD_SKU = "bai_card_sku";//
	 public static final String IS_VIRTUAL_GIFT = "isvirtualgift"; //虚拟赠品
	 public static final String IS_SWKYJ = "isswkyj";//上网卡硬件
	 public static final String DIC_SOURCE_TYPE = "DIC_SOURCE_TYPE";//订单来源映射接入类别
	 public static final String SHIPPING_TYPE = "shipping_type";//淘宝单配送方式转换
	 public static final String IS_VIRTUAL = "is_virtual";//分类映射虚拟货品
	 public static final String IS_HAVE_MSISDN= "ishavemsisdn";//有号码节点分类
	 public static final String IS_LIPIN = "islipin";//分类映射礼品
	 public static final String IS_BAIKA = "isbaikai";//合约机分类映射白卡、号卡是白卡的商品类型
	 public static final String SOURCE_TYPE = "source_type";//订单来源映射接入类型
	 public static final String IS_PAYED = "ispayed";//支付方式映射已支付
	 public static final String IS_4G_DIYTAOCAN= "is4gdiytaocan";//分类映射套餐、是否4G DIY套餐
	 public static final String PRODUCT_BRAND = "prod_brand";//分类映射产品品牌
	 public static final String IS_CHENG_KA = "ischengka";//老商城映射成卡
	 public static final String IS_YEWUBAO = "isyewubao";//是否业务包
	 public static final String IS_3G4GYTH = "is3g4gyth";//是否3G/4G一体化套餐
	 public static final String HEYUEJI = "heyueji";//分类映射是否合约机
	 public static final String CATID_IS4G = "catid_is4g";//分类映射套餐-是否4G套餐
	 public static final String IS_MOBILE = "is_mobile";//类型映射手机
	 public static final String IS_JTKH = "isjtkh";//订单来源映射集团客户
	 public static final String PLATFORM_STATUS = "platformstatus";//分类映射外部订单状态
	 public static final String IS_PHYSICAL = "is_physical";//实物货品
	 public static final String IS_PHYSICAL_ORDER = "is_physical_order";//实物单
	 public static final String IS_GIFT = "is_gift";//货品类型映射赠品
	 public static final String GIFT_TYPE = "gift_type";//分类映射赠品类型
	 public static final String DIC_AREA_CODE = "DIC_AREA_CODE";//
	 public static final String BSS_TID_CATEGORY = "bss_tid_category";//BSS订单类别映射
	 public static final String BSS_PAY_TYPE = "bss_pay_type";//BSS支付类型映射
	 public static final String BSS_IS_OLD = "bss_is_old";//BSS新老用户映射
	 public static final String ZB_INVOICE_PRINT_REL_TYPE = "ZB_INVOICE_PRINT_REL_TYPE";//总部发票打印方式映射发票类型
	 public static final String PACK_TYPE = "pack_type";//商品类型映射老系统商品包类型
	 public static final String DIC_ORDER_ORIGIN = "DIC_ORDER_ORIGIN";//商城来源映射关系
	 public static final String ACCESSORY_TYPE = "accessory_type";//配件分类映射总部配件类型
	 public static final String ZB_ORDER_ACC_TYPE = "ZB_ORDER_ACC_TYPE";//订单来源总部映射关系
	 public static final String ZB_CARRY_MODE = "ZB_CARRY_MODE";//总部配送方式映射
	 public static final String WMS_CARRY_MODE = "WMS_CARRY_MODE";//
	 public static final String BSS_AREA_CODE = "bss_area_code";//BSS订单来源地市映射关系
	 public static final String ZB_LOGISTICS_COMPANY_CODE = "ZB_LOGISTICS_COMPANY_CODE";//物流公司编码映射总部
	 public static final String ORDER_PAY_TYPE = "_order_pay_type";//总部支付类型映射
	 public static final String WMS_ORDER_TYPE = "wms_order_type";//WMS订单类型映射
	 public static final String ND_PAY_STATUS = "nd_pay_status";//南都支付状态映射
	 public static final String ND_SHIPPING_TYPE = "nd_shipping_type";//南都配送方式映射
	 public static final String LIANG_PRICE_MALL = "LIANG_PRICE_MALL";//透传靓号费的商城
	 
	//常用静态数据字典编码stype【es_dc_public_ext】
	 public static final String PAY_STATUS = "pay_status";//支付状态映射
	 public static final String SOURCE_FROM = "source_from";//	订单来源
	 public static final String ISPJ = "ispj";//	是否配件
	 public static final String ISLIPIN = "islipin";//	是否礼品
	 public static final String IS_TO4G = "is_to4g";//	是否2G、3G升4G
	 public static final String CERTI_TYPE = "certi_type";//	证件类型
	 public static final String DISCOUNTTYPE = "DiscountType";//	优惠活动类型
	 public static final String DIC_VIP_CARD_STATE = "DIC_VIP_CARD_STATE";//	卡状态
	 public static final String DIC_TEAM_TYPE = "DIC_TEAM_TYPE";//	团队类型
	 public static final String DIC_SYN_TYPE = "DIC_SYN_TYPE";//	同步状态
	 public static final String CUSTOMERTYPE = "CustomerType";//	客户类型
	 public static final String TRADE_TYPE = "TRADE_TYPE";//	交易类型
	 public static final String INTERFACE_NAME = "INTERFACE_NAME";//	接口名称
	 public static final String DIC_ELEMENT_TYPE = "DIC_ELEMENT_TYPE";//	元素类型
	 public static final String ACC_CON_CONSIGN_MODE = "ACC_CON_CONSIGN_MODE";//	托收方式
	 public static final String DIC_STOP_MODE = "DIC_STOP_MODE";//	催停方式
	 public static final String DIC_STEP_STATE = "DIC_STEP_STATE";//	环节状态
	 public static final String DIC_SPECIAL_BUSINESS_TYPE = "DIC_SPECIAL_BUSINESS_TYPE";//	特殊业务类型
	 //public static final String DIC_SOURCE_TYPE = "DIC_SOURCE_TYPE";//	接入类别
	 public static final String DIC_SDS_COMP = "DIC_SDS_COMP";//	闪电送物流公司
	 public static final String DIC_QUQLITY = "DIC_QUQLITY";//	质量是否满足要求
	 public static final String DIC_PRODUCT_STATUS = "DIC_PRODUCT_STATUS";//	订单商品状态
	 public static final String DIC_POST_PAY_MODE = "DIC_POST_PAY_MODE";//	快递费用支付方式
	 public static final String DIC_PAY_STATUS = "DIC_PAY_STATUS";//	支付状态
	 public static final String DIC_ORODER_PAY_TYPE = "DIC_ORODER_PAY_TYPE";//	付费类型
	 public static final String DIC_ORDER_CHANGE = "DIC_ORDER_CHANGE";//	变更类型
	 public static final String DIC_NODE_START_TYPE = "DIC_NODE_START_TYPE";//	环节开始类型
	 public static final String DIC_NODE_END_TYPE = "DIC_NODE_END_TYPE";//	环节结束类型
	 public static final String DIC_HANDLE_TYPE_M = "DIC_HANDLE_TYPE_M";//	退款确认处理意见类型
	 public static final String DIC_HANDLE_TYPE_B = "DIC_HANDLE_TYPE_B";//	客户回访处理意见类型
	 public static final String DIC_GROUP_STATE = "DIC_GROUP_STATE";//	集团状态
	 public static final String DIC_FLAG_ALARM = "DIC_FLAG_ALARM";//	是否报警
	 public static final String SHIPPING_COMPANY = "shipping_company";//	物流公司
	 //public static final String IS_VIRTUAL = "is_virtual";//	是否虚拟货品
	 public static final String IS_CHANGE = "is_change";//	是否变更套餐
	 public static final String ISWX = "isWX";//	是否无需配送
	 public static final String FIRSTMONBILLMODE = "FirstMonBillMode";//	首月资费方式
	 public static final String DIC_VIP_TYPE_CODE = "DIC_VIP_TYPE_CODE";//	维系等级
	 public static final String SYS_OPRACTION = "SYS_OPRACTION";//	操作动作
	 public static final String RESULT_LEVEL = "RESULT_LEVEL";//	评价级别
	 public static final String RECOVERTY_TYPE = "RECOVERTY_TYPE";//	资料收回方式
	 public static final String ORDER_PRI = "ORDER_PRI";//	订单优先级
	 public static final String DIC_ALERT_CONFIG_TYPE = "DIC_ALERT_CONFIG_TYPE";//	预警配置类型
	 public static final String NET_TYPE = "net_type";//	网别
	 public static final String ACCT_BAL_PRIVATE_TAG = "ACCT_BAL_PRIVATE_TAG";//	私有标志
	 public static final String DIC_RES_STATE = "DIC_RES_STATE";//	资源状态
	 public static final String DIC_RESOURCE_TYPE = "DIC_RESOURCE_TYPE";//	资源类型
	 public static final String DIC_ORDER_POST_TYPE = "DIC_ORDER_POST_TYPE";//	补寄类型
	 public static final String DIC_ON_INTERNET_TIME = "DIC_ON_INTERNET_TIME";//	上网卡时间
	 public static final String DIC_MT_STOREHOUSE = "DIC_MT_STOREHOUSE";//	仓库
	 public static final String DIC_MATIERL = "DIC_MATIERL";//	资料是否齐全
	 public static final String DIC_MAIN_FACTOR = "DIC_MAIN_FACTOR";//	主核因子
	 public static final String DIC_HANDLE_TYPE_H = "DIC_HANDLE_TYPE_H";//	发货处理意见类型
	 public static final String DIC_HANDLE_TYPE_F = "DIC_HANDLE_TYPE_F";//	质检稽核处理意见类型
	 public static final String DIC_HANDLE_TYPE_E = "DIC_HANDLE_TYPE_E";//	拣货出库处理意见类型
	 public static final String DIC_HANDLE_TYPE_A = "DIC_HANDLE_TYPE_A";//	预处理处理意见类型
	 public static final String DIC_GIFT_PROD_TYPE = "DIC_GIFT_PROD_TYPE";//	礼品卡产品类别
	 public static final String SHIPPING_TIME = "shipping_time";//	配送时间
	 public static final String SHIPPING_QUICK = "shipping_quick";//	是否闪电送
	 public static final String GOODS_TYPE = "goods_type";//	商品系统-商品大类
	 public static final String DIC_TRACE_STATUS = "DIC_TRACE_STATUS";//	跟进状态
	 public static final String MT_STATUS = "MT_STATUS";//	物料管理状态
	 public static final String DIC_CODFLAG = "DIC_CODFLAG";//	是否到付款
	 public static final String DIC_BESPOKE_FLAG = "DIC_BESPOKE_FLAG";//	是否预约单
	 public static final String DIC_ACCOUNT_TYPE = "DIC_ACCOUNT_TYPE";//	账号类型
	 public static final String DIC_STORAGE_TYPE = "DIC_STORAGE_TYPE";//	出入库类型
	 public static final String DIC_REMINDINFO_STATE = "DIC_REMINDINFO_STATE";//	预警信息的状态
	 public static final String DIC_REFUND_DEAL_TYPE = "DIC_REFUND_DEAL_TYPE";//	退单处理类型
	 public static final String DIC_RED_CUST_TAG = "DIC_RED_CUST_TAG";//	红名单客户标记
	 public static final String DIC_REAL_GROUP_TAG = "DIC_REAL_GROUP_TAG";//	真实集团标记
	 public static final String DIC_RATE_RESULT = "DIC_RATE_RESULT";//	评价结果
	 public static final String DIC_PARTICIPATE_ACTIVITY = "DIC_PARTICIPATE_ACTIVITY";//	参与活动
	 public static final String DIC_ORDER_EXCEPTION_TYPE = "DIC_ORDER_EXCEPTION_TYPE";//	异常订单异常类型
	 public static final String DIC_OPER_MODE = "DIC_OPER_MODE";//	生产模式规则
	 public static final String DIC_NATURE = "DIC_NATURE";//	性质
	 public static final String DIC_IS_COLLECTION = "DIC_IS_COLLECTION";//	是否托收
	 public static final String DIC_INDUSTRY_CD = "DIC_INDUSTRY_CD";//	客户行业
	 public static final String DIC_FIN_POLICY_LOC = "DIC_FIN_POLICY_LOC";//	促销政策地
	 public static final String ISVIRTUALGIFT = "isvirtualgift";//	是否虚拟赠品
	 public static final String ISTAOCAN = "istaocan";//	是否套餐
	 public static final String ISSWKYJ = "isswkyj";//	是否上网卡硬件
	 public static final String ISFUND_TYPE = "isfund_type";//	基金类型
	 public static final String INVOICE_PRINT_TYPE = "invoice_print_type";//	发票打印方式
	 public static final String SALEMODE = "SaleMode";//	销售方式
	 public static final String PAYMENT_CODE = "payment_code";//	支付机构编码
	 public static final String DIC_WARNING_COLOR = "DIC_WARNING_COLOR";//	预警颜色
	 public static final String DIC_VIP_CLASS_ID = "DIC_VIP_CLASS_ID";//	会员卡级别
	 public static final String DIC_USER_TYPE = "DIC_USER_TYPE";//	用户类型
	 public static final String DIC_USER_NUM = "DIC_USER_NUM";//	用户数
	 public static final String DIC_SUB_BUSIN_TYPE = "DIC_SUB_BUSIN_TYPE";//	业务子类
	 public static final String SYS_OPRSTATE = "SYS_OPRSTATE";//	操作状态
	 public static final String REMOVE_REASON = "REMOVE_REASON";//	离网原因
	 public static final String PRINT_MODEL_TYPE = "PRINT_MODEL_TYPE";//	模板类型
	 public static final String OPERATORS_TYPE = "OPERATORS_TYPE";//	运营商
	 public static final String MAN_INTR = "MAN_INTR";//	兴趣爱好
	 public static final String DIC_BL_FLAG = "DIC_BL_FLAG";//	操作动作
	 public static final String DIC_ALERT = "DIC_ALERT";//	预警大类
	 public static final String DEPART_TYPE_CODE = "DEPART_TYPE_CODE";//	部门类型编码
	 public static final String BUSI_TYPE = "BUSI_TYPE";//	业务类型
	 public static final String DIC_SUB_ORDER_TYPE = "DIC_SUB_ORDER_TYPE";//	BSS订单类别
	 public static final String DIC_SOURCE_FROM_SYSTEM = "DIC_SOURCE_FROM_SYSTEM";//	数据来源系统
	 public static final String DIC_SMSBROADCAST_RESULT = "DIC_SMSBROADCAST_RESULT";//	短信群发结果
	 public static final String DIC_SELL_CONTRACT_SORT = "DIC_SELL_CONTRACT_SORT";//	销售合同分类
	 public static final String DIC_PRODUCT_AGREEMENT_DATE = "DIC_PRODUCT_AGREEMENT_DATE";//	合约期
	 public static final String DIC_POST_MODE = "DIC_POST_MODE";//	邮寄方式
	 public static final String DIC_PAYMENT_DS = "DIC_PAYMENT_DS";//	代收款结算方式
	 public static final String DIC_ORDER_NODE = "DIC_ORDER_NODE";//	订单环节
	 public static final String DIC_ORDER_BUSI_STATUS = "DIC_ORDER_BUSI_STATUS";//	订单业务商品状态
	 public static final String DIC_MT_DEPARTMENT = "DIC_MT_DEPARTMENT";//	科室
	 public static final String DIC_HANDWORK_SEND_OUT_FLAG = "DIC_HANDWORK_SEND_OUT_FLAG";//	是否已发货
	 public static final String DIC_CUST_STATE = "DIC_CUST_STATE";//	商机客户状态
	 public static final String DIC_CUSTOMER_SEX = "DIC_CUSTOMER_SEX";//	性别
	 public static final String DIC_CREDIT_CLASS = "DIC_CREDIT_CLASS";//	信用等级
	 //public static final String SHIPPING_TYPE = "shipping_type";//	配送方式
	 //public static final String HEYUEJI = "heyueji";//	是否合约机
	 public static final String DELIVERY_STATUS = "delivery_status";//	发货状态
	 public static final String PRODUCTTYPE = "ProductType";//	产品类型
	 public static final String PRODUCTBRAND = "ProductBrand";//	产品品牌
	 public static final String FEEID = "FeeID";//	收费项编码
	 public static final String DIC_TASK_STATUS = "DIC_TASK_STATUS";//	任务状态
	 public static final String ORDER_EXCEPTION = "ORDER_EXCEPTION";//	订单异常类型
	 public static final String GIFT_ERROR_CODE = "GIFT_ERROR_CODE";//	礼品异常类型
	 public static final String DIC_BIRTH_TYPE = "DIC_BIRTH_TYPE";//	生日类别
	 public static final String DICT_ACCOUNT_TYPE = "DICT_ACCOUNT_TYPE";//	开户类型
	 public static final String ACC_CON_LIMIT_MODE = "ACC_CON_LIMIT_MODE";//	限定使用方式
	 public static final String DIC_SPEC_MARKET_FLAG = "DIC_SPEC_MARKET_FLAG";//	特定市场标记
	 public static final String DIC_RECOMM_TYPE = "DIC_RECOMM_TYPE";//	推荐方式
	 public static final String DIC_PROV_CENTER_BUSI_PROPERTY = "DIC_PROV_CENTER_BUSI_PROPERTY";//	省中心行业属性
	 public static final String DIC_PROCESS_TYPE = "DIC_PROCESS_TYPE";//	加工类型
	 public static final String DIC_ORG_TYPE = "DIC_ORG_TYPE";//	部门类型
	 public static final String DIC_ORDER_REFUND_STATUS = "DIC_ORDER_REFUND_STATUS";//	订单退货状态
	 public static final String DIC_ORDER_HANG_REASON = "DIC_ORDER_HANG_REASON";//	订单挂起原因
	 public static final String DIC_MATERIAL_RETRIEVE = "DIC_MATERIAL_RETRIEVE";//	回收资料
	 public static final String DIC_INFO_STATUS = "DIC_INFO_STATUS";//	财务对账记录状态
	 public static final String DIC_GIFT_SPECIES = "DIC_GIFT_SPECIES";//	礼品种类
	 public static final String DIC_EDU_RECODE = "DIC_EDU_RECODE";//	学历
	 public static final String DIC_CUSTOMIZATION = "DIC_CUSTOMIZATION";//	社会机定制机
	 public static final String ISYEWUBAO = "isyewubao";//	是否业务包
	 public static final String INVOICE_TYPE = "invoice_type";//	发票类型
	 public static final String CHENG_CARD_SKU = "cheng_card_sku";//	成卡SKU类型,白卡SKU类型,成卡SKU类型
	 public static final String RELIEFPRESFLAG = "ReliefPresFlag";//	减免预存标记
	 public static final String ISCUSTOMIZED = "IsCustomized";//	是否为定制机
	 public static final String GOODSTYPE = "GoodsType";//	总部商品类型
	 public static final String GIFTTYPE = "GiftType";//	赠品类型
	 public static final String ORDERACCTYPE = "OrderAccType";//	订单接入类别
	 public static final String DIC_WHITE_CARD_TYPE = "DIC_WHITE_CARD_TYPE";//	号卡类型
	 public static final String DIC_WARNING_TYPE = "DIC_WARNING_TYPE";//	预警类型
	 public static final String WORKTASK_STATE = "WORKTASK_STATE";//	待办工作状态
	 public static final String TYPE_CODE = "TYPE_CODE";//	角色类型编码
	 public static final String ORG_TYPE_CODE = "ORG_TYPE_CODE";//	组织类型
	 public static final String MEMORY_UNIT = "MEMORY_UNIT";//	内存的单位
	 public static final String DIC_APPROVE_LEVEL = "DIC_APPROVE_LEVEL";//	满意度
	 public static final String DIC_ALERT_STATE = "DIC_ALERT_STATE";//	预警规则状态
	 public static final String DIC_ALERT_CYCLE = "DIC_ALERT_CYCLE";//	预警周期
	 public static final String DIC_ACTIVE_SORT = "DIC_ACTIVE_SORT";//	生效方式
	 public static final String DICT_ACCOUNT_4G_TYPE = "DICT_ACCOUNT_4G_TYPE";//	4G开户类型
	 public static final String DIC_GIFT_ENTITY_TYPE = "DIC_GIFT_ENTITY_TYPE";//	实物
	 public static final String DIC_ORDER_EXT_STATUS = "DIC_ORDER_EXT_STATUS";//	外部订单状态
	 public static final String DIC_SPEC_MARKET_LEVEL = "DIC_SPEC_MARKET_LEVEL";//	特定市场等级
	 public static final String DIC_REISSUE_TYPE = "DIC_REISSUE_TYPE";//	补寄类型
	 public static final String DIC_PROV_CENTER_CUST_TYPE = "DIC_PROV_CENTER_CUST_TYPE";//	省中心客户类型
	 public static final String DIC_ORDER_USER_TYPE = "DIC_ORDER_USER_TYPE";//	用户类型
	 public static final String DIC_ORDER_NEW_TYPE = "DIC_ORDER_NEW_TYPE";//	订单类型
	 public static final String DIC_ORDER_INST_FLOW_TYPE = "DIC_ORDER_INST_FLOW_TYPE";//	流程类型
	 public static final String DIC_ORDER_DEAL_TYPE = "DIC_ORDER_DEAL_TYPE";//	订单处理类型
	 public static final String DIC_MATERIAL_TYPE = "DIC_MATERIAL_TYPE";//	资料类型
	 public static final String DIC_LIGHT_NING_STATUS = "DIC_LIGHT_NING_STATUS";//	闪电送状态
	 public static final String DIC_HANDLE_TYPE_K = "DIC_HANDLE_TYPE_K";//	售后回访处理意见类型
	 public static final String DIC_HANDLE_TYPE_C = "DIC_HANDLE_TYPE_C";//	预拣货处理意见类型
	 public static final String DIC_FIN_VOUCHER_TYPE = "DIC_FIN_VOUCHER_TYPE";//	优惠方式
	 public static final String DIC_DOC_TYPE = "DIC_DOC_TYPE";//	文档类型
	 public static final String PAY_TYPE = "pay_type";//	支付类型
	 public static final String CARD_TYPE = "card_type";//	号卡性质
	 public static final String OFFER_EFF_TYPE = "offer_eff_type";//	首月资费方式
	 public static final String ISHAVEMSISDN = "ishavemsisdn";//	是否有号码节点
	 //public static final String IS_TO4G = "is_to4g";//	是否2G、3G升5G
	 //public static final String IS_MOBILE = "is_mobile";//	是否手机
	 public static final String ELEMENTTYPE = "ElementType";//	元素类型
	 public static final String PAY_WAY = "pay_way";//	支付方式
	 public static final String DIC_VISIT_TYPE = "DIC_VISIT_TYPE";//	生效方式
	 public static final String DIC_TASK_TYPE = "DIC_TASK_TYPE";//	任务类型
	 public static final String PASS_TYPE = "PASS_TYPE";//	客户证件类型
	 public static final String OBJECT_TYPE = "OBJECT_TYPE";//	考核对象类型
	 public static final String MATERIAL_VERIFY_STATE = "MATERIAL_VERIFY_STATE";//	资料审核状态
	 public static final String LEVEL_TYPE = "LEVEL_TYPE";//	级别类型
	 public static final String DIC_ZONE_PROVINCE_CD = "DIC_ZONE_PROVINCE_CD";//	省仓
	 public static final String DIC_YIDONG_DEAL = "DIC_YIDONG_DEAL";//	异动处理
	 public static final String DIC_WORK_LEVEL = "DIC_WORK_LEVEL";//	工作级别
	 public static final String DIC_BILL_MAIL_TYPE = "DIC_BILL_MAIL_TYPE";//	寄送方式
	 public static final String DIC_ALERT_TYPE = "DIC_ALERT_TYPE";//	预警类型
	 public static final String DIC_ALERT_LEVEL = "DIC_ALERT_LEVEL";//	预警级别
	 public static final String PRO_TYPE = "Pro_type";//	总部--货品类型
	 public static final String ACC_CON_PAY_MODE = "ACC_CON_PAY_MODE";//	帐户付费类型
	 public static final String DIC_SP_DEL = "DIC_SP_DEL";//	特殊处理
	 public static final String DIC_SOCIETY_FLAG = "DIC_SOCIETY_FLAG";//	是否社会机
	 public static final String DIC_SELL_CONTRACT_TYPE = "DIC_SELL_CONTRACT_TYPE";//	销售合同类型
	 public static final String DIC_PLAN_TYPE = "DIC_PLAN_TYPE";//	计划类型
	 public static final String DIC_ORDER_STATUS = "DIC_ORDER_STATUS";//	订单状态
	 public static final String DIC_ITEM_TYPE = "DIC_ITEM_TYPE";//	帐目类型
	 public static final String DIC_HANDWORK_RECORD_STATUS = "DIC_HANDWORK_RECORD_STATUS";//	有效状态
	 public static final String DIC_HANDLE_TYPE_J = "DIC_HANDLE_TYPE_J";//	回单处理意见类型
	 public static final String DIC_GIFT_UNIT = "DIC_GIFT_UNIT";//	赠品面值
	 public static final String ISZBMALL = "iszbmall";//	总部商城编码
	 public static final String CHANNEL_MARK = "channel_mark";//	渠道标记,订单发展渠道
	 public static final String ACTIVITYTYPE = "ActivityType";//	合约类型
	 public static final String DIC_WM_FEE_TYPE = "DIC_WM_FEE_TYPE";//	费用类型
	 public static final String DIC_TRANSPORT_STATUS = "DIC_TRANSPORT_STATUS";//	物流状态
	 public static final String DIC_TEAM_MEM_TYPE = "DIC_TEAM_MEM_TYPE";//	团队成员类型
	 public static final String TARGET_TYPE = "TARGET_TYPE";//	考核指标类型
	 public static final String REF_TYPE = "REF_TYPE";//	法人代表证件类型
	 public static final String ORDER_TYPE_LH = "ORDER_TYPE_LH";//	订单类型(靓号)
	 public static final String JOB_TYPE = "JOB_TYPE";//	经理职位类别
	 public static final String ID_TYPE = "ID_TYPE";//	标识类型
	 public static final String DIC_CARRY_STATUS = "DIC_CARRY_STATUS";//	配送状态
	 public static final String DIC_ACCT_STATE = "DIC_ACCT_STATE";//	帐户状态
	 public static final String ERR_TYPE = "Err_type";//	异常类型
	 public static final String USER_TYPE = "user_type";//	入网类型
	 public static final String DIC_BANK_NAME = "DIC_BANK_NAME";//	BSS托收银行
	 public static final String DIC_GIFT_CARD_TYPE = "DIC_GIFT_CARD_TYPE";//	礼品卡种类
	 public static final String DIC_PROV_NAME_CUST_TYPE = "DIC_PROV_NAME_CUST_TYPE";//	省名单制客户类型
	 public static final String DIC_POST_TAG = "DIC_POST_TAG";//	邮寄标记
	 public static final String DIC_PLAN_TIME_TYPE = "DIC_PLAN_TIME_TYPE";//	时间类型
	 public static final String DIC_PAY_MODE = "DIC_PAY_MODE";//	付费方式/帐户类型
	 public static final String DIC_MT_STATUS = "DIC_MT_STATUS";//	物料状态
	 public static final String DIC_IS_UPLOAD = "DIC_IS_UPLOAD";//	客户资料是否上传
	 public static final String DIC_IS_SHOW_GIFT = "DIC_IS_SHOW_GIFT";//	是否补寄
	 public static final String DIC_IN_NET_MODE = "DIC_IN_NET_MODE";//	入网方式
	 public static final String DIC_INFO_SOURCE = "DIC_INFO_SOURCE";//	财务对账记录来源
	 public static final String DIC_HANDLE_TYPE_D = "DIC_HANDLE_TYPE_D";//	业务受理处理意见类型
	 public static final String DIC_GROUP_BUSIN_TYPE = "DIC_GROUP_BUSIN_TYPE";//	集团行业类型
	 public static final String DIC_GIFT_OPERATE_TYPE = "DIC_GIFT_OPERATE_TYPE";//	礼品卡出入库操作类型
	 
	 public static final String ZB_ACTIVITY_TYPE = "ZB_ACTIVITY_TYPE";//合约计划总部映射
	 public static final String IS_CUSTOMIZED = "is_customized";//分类定制机映射
	 public static final String OTHER_SHIP_CITY = "other_ship_city";//非广东地市
	 public static final String ACTIVE_SORT = "active_sort";//生效方式
	 public static final String IS_IPHONE_PLAN = "is_iphone_plan";//是否iphone套餐
	 public static final String ABNORMAL_STATUS = "abnormal_status";//异常状态
	 public static final String ZB_INVOICE_TYPE = "ZB_INVOICE_TYPE";//总部发票类型映射
	 public static final String ORDER_TYPE = "order_type";//商城订单类型与订单系统订单类型字典映射

	 public static final String IS_INSUR = "is_insur";//	是否保价
	 public static final String IS_COD = "is_cod";//	是否代收
	 public static final String POST_COMP = "post_comp";//	发货单位
	 public static final String ORDER_SUPPLY_STATUS = "order_supply_status";//	补寄状态
	 public static final String IS_ORDER_HIS = "is_order_his";//	是否是历史单

	 public static final String ZB_PROD_TYPE = "zb_prod_type";//总部货品类型
	 public static final String ZB_FLOW_NODE = "zb_flow_node";//总部流程环节
	 
	 public static final String OPERATOR_CODE = "operator_code";//操作人编码
	 public static final String DIC_SUPPLIER_ID = "DIC_SUPPLIER_ID";//用于配置的供应商ID
	 
	 public static final String CBSS_LOGIN_USER_INFO = "cbss_login_user_info"; // cBSS系统操作用户登录信息
	 
}
