package com.ztesoft.net.mall.core.model;

/**
 * Logi generated by MyEclipse - Hibernate Tools
 */

public class Logi implements java.io.Serializable {

	private String id;

	private String name;
	
	private String key_str;
	
	private String company_code;
	
	
	public String getKey_str() {
		return key_str;
	}

	public void setKey_str(String key_str) {
		this.key_str = key_str;
	}

	public String getCompany_code() {
		return company_code;
	}

	public void setCompany_code(String company_code) {
		this.company_code = company_code;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	 

    
}