package com.ztesoft.net.mall.core.model;



/**
 * PayCfg generated by MyEclipse - Hibernate Tools
 */

public class PayCfg  implements java.io.Serializable {


    // Fields    

    protected String id;

	protected String name;

	protected String config;

	protected String biref;

	protected Double pay_fee;

	protected String type;
	
	private String cfg_prop;
	private String tip_inf;
	private String online_flag;
	private String bank_adss;

	public String getBiref() {
		return biref;
	}

	public void setBiref(String biref) {
		this.biref = biref;
	}
	public String getConfig() {
		return config;
	}
	public void setConfig(String config) {
		this.config = config;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Double getPay_fee() {
		return pay_fee;
	}
	public void setPay_fee(Double pay_fee) {
		this.pay_fee = pay_fee;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}

	public String getCfg_prop() {
		return cfg_prop;
	}

	public void setCfg_prop(String cfg_prop) {
		this.cfg_prop = cfg_prop;
	}

	public String getTip_inf() {
		return tip_inf;
	}

	public void setTip_inf(String tip_inf) {
		this.tip_inf = tip_inf;
	}

	public String getOnline_flag() {
		return online_flag;
	}

	public void setOnline_flag(String online_flag) {
		this.online_flag = online_flag;
	}

	public String getBank_adss() {
		return bank_adss;
	}

	public void setBank_adss(String bank_adss) {
		this.bank_adss = bank_adss;
	}


}