package com.ztesoft.net.ecsord.params.ecaop.resp.orderReceiveBack;

public class UNI_BSS_BODY {

	private ORDER_RECEIVE_BACK_RSP ORDER_RECEIVE_BACK_RSP;

	public ORDER_RECEIVE_BACK_RSP getORDER_RECEIVE_BACK_RSP() {
		return ORDER_RECEIVE_BACK_RSP;
	}

	public void setORDER_RECEIVE_BACK_RSP(ORDER_RECEIVE_BACK_RSP oRDER_RECEIVE_BACK_RSP) {
		ORDER_RECEIVE_BACK_RSP = oRDER_RECEIVE_BACK_RSP;
	}

}