package com.ztesoft.net.mall.core.model;

/**
 * DlyArea generated by MyEclipse - Hibernate Tools
 */

public class DlyArea implements java.io.Serializable {

	private String area_id;

	private String name;

	public String getArea_id() {
		return area_id;
	}

	public void setArea_id(String areaId) {
		area_id = areaId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

    
}